name: pokedex
description: A Pokedex flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: 2.10.5

dependencies:
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  fluentui_system_icons: ^1.1.161
  lottie: ^1.2.2
  syncfusion_flutter_gauges: ^20.1.50
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  animations: ^2.0.2

  get: ^4.6.1
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  dartz: ^0.10.1
  connectivity_plus: ^2.2.1
  url_launcher: ^6.0.20
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  _fe_analyzer_shared: ^38.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
